### ISSUE TITLE
[CT-1628] Update to work with consolidated Parsed and Compiled node classes

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-rpc#102]
In dbt-core/#6384 we are consolidating the Parsed and Compiled node classes as part of the cleanup for creating standard protobuf artifacts for nodes. We need to rename the files and classes for a number of objects.

**Comment by jtcohen6** [comment]
Resolved by https://github.com/dbt-labs/dbt-rpc/pull/103
