### ISSUE TITLE
[CT-1730] RPC Failure after recent update to source JSON-RPC JSONRPCResponseManager class

### ISSUE THREAD

**Issue by anubhavsharma515** [dbt-labs/dbt-rpc#116]
Good day and Merry Christmas!

On merging in https://github.com/pavlov99/json-rpc/pull/122, it seems like there was a modification to the `JSONRPCResponseManager` class which the `dbt_rpc/response_manager` inherits from: 

https://github.com/dbt-labs/dbt-rpc/blob/43a13999441268d220236bc230791554daa78320/dbt_rpc/rpc/response_manager.py#L69-L88

As a result an error of the form 
`_get_responses() takes 3 positional arguments but 4 were given` is being thrown.

I'm not sure how to help resolve this, but I believe it should be a fairly straightforward fix? Would really appreciate help with this as our project's orchestration relies on the dbt-core and the rpc server.

**Comment by dima898** [comment]
Hi! Would also appreciate the fix for this issue. @anubhavsharma515 For now as a workaround, downgrading json-rpc package to version 1.12.1 worked for me.

**Comment by anubhavsharma515** [comment]
Hey @dima898, thanks so much for the advice - thats exactly what I did after a few days of failures 🙂 . Just for your context, I have a PR up #118 that I believe fixes this issue.
