### ISSUE TITLE
[CT-1863] Support dbt-core 1.5 in `dbt-rpc`

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-rpc#122]
As the exploration we did with #113, it is possible to continue supporting `dbt-core` for one more version with `dbt-rpc`.
As the API-ification project moving on, there are likely new things that we need to adjust to make `dbt-rpc` working(i.e. manifest got refactored).
This work should be estimated and being worked on after we merge `feature/click-cli` in `dbt-core` to `main`.

We should make sure all integration tests in `dbt-rpc` pass with latest `main` branch of `dbt-core`

**Comment by iknox-fa** [comment]
LG 1/30/2023 @ChenyuLInx and @stu-k are going to pair and better refine this ticket for grooming next time.

**Comment by stu-k** [comment]
I pushed the changes I _think_ fix the change to manifest generation abstraction to [this](https://github.com/dbt-labs/dbt-rpc/compare/CT-1863/tasks-use-manifest?expand=1) branch. Any work around this should probably be relegated to testing!

**Comment by iknox-fa** [comment]
After more code diving we discovered that we override __init__ so the change in function sig isn't an issue.
