### ISSUE TITLE
[CT-2324] dbt-rpc is not working on apple mac [intel]

### ISSUE THREAD

**Issue by sivankumar86** [dbt-labs/dbt-rpc#126]
Hi Team,
    I am trying to test dpt-rpc==0.2.1 with dbt==1.3.3 but, I am unable to start server and fire any command

1. python 3.8 
2. pip install dbt-core==1.3.3
3. pip install dbt-rpc==0.2.1
4. dbt-rpc -d serve
 [no output] and just hang 

am i missing anything and is there any security block ? Could you shed somelight on this ?

**Comment by jtcohen6** [comment]
@sivankumar86 You need to enable "legacy logging" for use with `dbt-rpc`. Try this:
```
$ DBT_ENABLE_LEGACY_LOGGER=1 dbt-rpc serve
```
Heads up that `dbt-rpc` is soon to be deprecated! While we are planning to offer backwards compatibility up through dbt-core v1.5, we are _not_ planning to support it with v1.6.
