### ISSUE TITLE
[CT-2344] Compilation Error in rpc request (from remote system.sql) 

### ISSUE THREAD

**Issue by QingSun88** [dbt-labs/dbt-rpc#127]
**Background:** 
  I am using a dbt package 'Velir/ga4', so I follow the steps below:
add package to packages.yml →change required variables in project's dbt_project.yml file→run ‘dbt deps’ → run ‘dbt seed’ -->run models
![image](https://user-images.githubusercontent.com/60782937/229124880-5764c17c-ee4b-4d69-8fc0-fb13594268d9.png)

**problem:**
All is good and I can run these models and create tales in my data warehouse BigQuery. But some of these models can be compiled and previewed, but some cannot.
When compiling or previewing ‘**base_ga4__events.sql**’, it shows “**Compilation Error in rpc request (from remote system.sql) Required var 'start_date' not found in config**”. But actually, I have set the var ‘start_date’ when I change required variables in the project's dbt_project.yml file under the main file tree.
When compiling or previewing ‘**stg_ga4__events.sql’**, it shows “**Compilation Error in rpc request (from remote system.sql) 'extract_page_path' is undefined**”. But actually, this package has already defined it in a macro folder.

Also when compiling or previewing some other models which require optional variables defined in the dbt_project.yml file, like ‘**stg_ga4__derived_session_properties.sql**', ‘**stg_ga4__page_conversions.sql**',‘**stg_ga4__user_properties.sql** , I meet another similar error shows '**Runtime Error got an update_rpc call with an unrecognized rpc: rpc.<project>.request**'
![image](https://user-images.githubusercontent.com/60782937/229128854-e8b022c9-0e7c-4cc0-aa49-324d720313f6.png)

Hope can get help here to solve this issue.

**Comment by jtcohen6** [comment]
@QingSun88 I'm not exactly sure what's going on here, sorry :(

I also want to be honest and say that we're no longer providing support for `dbt-rpc`, as it's slated for deprecation. We're effectively replacing it with better programmatic interfaces in `dbt-core`.

You can read the docs for this, which is new in v1.5 (currently available as a release candidate): https://docs.getdbt.com/reference/programmatic-invocations
