### ISSUE TITLE
[CT-2880] Defer not working with dbt 1.4 and 1.5

### ISSUE THREAD

**Issue by gshank** [dbt-labs/dbt-rpc#147]
The ref in a model used with defer is not resolving properly for dbt 1.4.

`dbt run -s baz --defer --state prod`

In 1.3 it uses the prod table:
create table development.dbt_jyeo.baz as (
  select * from analytics.marts.foo
  union all
  select * from analytics.marts.bar
)

in 1.4 it doesn't resolve properly:
create table development.dbt_jyeo.baz as (
  select * from development.dbt_jyeo.foo
  union all
  select * from development.dbt_jyeo.bar
)

**Comment by yuna-tang** [comment]
We have the same issue with dbt 1.4 too. We have rolled back to dbt 1.3 to be able to use the --defer in the cloud IDE.
