### ISSUE TITLE
Support compiling/executing SQL in the context of a model

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-rpc#46]
### Describe the feature
Today, the rpc server supports compiling/executing SQL in the context of a dbt project. This is good! Unfortunately, dbt uses a fake/stub compilation context for these compile/execute tasks, so model-specific variables like `this` or macros like `is_incremental()` return incorrect values in compilation. Instead, the rpc server should provide a mechanism for specifying the node (eg. by unique_id or path) which should provide the compilation context for the rpc method.

### Describe alternatives you've considered
Not sure how else something like this could work... possibly by providing a set of context overrides alongside the rpc call? 

### Additional context
- Applies on all databases
- Would be most useful for interactive development use-cases for the rpc server, like in the dbt Cloud IDE (or similar)

### Who will this benefit?
Users who leverage the rpc server as a part of their dbt code development workflow; dbt Cloud users

### Are you interested in contributing this feature?
I would be happy to help :)

**Comment by saraleon1** [comment]
+1 dbt Cloud user

User is trying to access `{{ model.name }}` in a macro, and when they are testing their macro development in cloud via the preview and compilation functions in the IDE, they see this return as `request` rather than the actual model name.

**Comment by jeremyyeo** [comment]
A customer reached out about `this` so I'd just record this loom to show that preview/compile indeed does not resolve correctly (but when the model is built - it does resolve correctly).

https://www.loom.com/share/14163a6a4f604d70bf4613114db11f8f
