### ISSUE TITLE
--vars for dbt_project.yml configs: CLI works, RPC doesn't

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-rpc#48]
In dbt-labs/dbt#2265, we found that when a `--vars` value changed attributes of the parsed manifest, the RPC server needed to reload/rewrite that manifest. This wasn't an issue with partial parsing—the files were correctly invalidated—but still the server took the manifest parsed by `dbt rpc` as its starting point, when `--vars` can override key configurations in that manifest. The fix for this, in dbt-labs/dbt#2363, impacted the performance of the `cli_args` RPC method accordingly.

It seems that the "reload" is still not working for **dbt_project.yml**, however, or at least for its configs that contain `{{var()}}` calls. In general, using `vars` within the project file can be quite tricky today. The parsing/rendering order is not clear (#3105). We should do core work here to rationalize and clarify when `vars` are set, and when they're available (#2955).

In the meantime, we should figure out why RPC behavior is not consistent with CLI behavior.

### Steps To Reproduce

In **models/my_model.sql**:
```sql
select '{{ var("my_var", "foo") }}'
```

In **dbt_project.yml**:
```yml
models:
  my_project:
    +schema: "{{ var('my_var', 'foo') }}"
```

#### CLI
```
$ dbt run --vars '{my_var: bar}'
```
```
  create view "jerco"."dbt_jcohen_bar"."my_model__dbt_tmp" as (
    select 'bar'
  );
```

#### RPC

Request:
```
{
    "jsonrpc": "2.0",
    "method": "cli_args",
    "id": "2db9a2fe-9a39-41ef-828c-25e04dd6b07d",
    "params": {
        "timeout": 60,
        "cli": "run --vars '{my_var: bar}'"
    }
}
```
Poll for result:
```json
{
    "result": {
        ...
        "logs": [
            ...
            {
                "message": "On model.my_project.my_model: /* {\"app\": \"dbt\", \"dbt_version\": \"0.19.0\", \"profile_name\": \"garage-postgres\", \"target_name\": \"dev\", \"node_id\": \"model.my_project.my_model\"} */\n\n  create view \"jerco\".\"dbt_jcohen_foo\".\"my_model__dbt_tmp\" as (\n    select 'bar'\n  );\n",
                ...
            },
            ...
        ],
        "results": [
            {
                "node": {
                    "schema": "dbt_jcohen_foo",
                    "compiled_sql": "select 'bar'",
                    "relation_name": "\"jerco\".\"dbt_jcohen_foo\".\"my_model\"",
                    ...
                },
                ...
            },
            ...
        ]
    }
}
```

Of course, there's one impractical way to get this to work in the meantime:
```
$ dbt rpc --vars '{my_var: bar}'
```
Then a simple `run` method returns the expected result.

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.19.0
   latest version: 0.19.0

Up to date!
```

**Comment by vrichmond499** [comment]
Another bump!

**Comment by jeremyyeo** [comment]
As of `dbt-core==1.0.0`, `--vars` aren't correctly parsed by the rpc server / dbt Cloud.

### Setup

```yml
# sources.yml
version: 2

sources:
  - name: my_sources
    database: "{{ var('db_name', 'foo') }}"
    schema: dbt_jyeo
    tables:
      - name: my_source
```

```sql
-- my_model.sql
select * from {{ source('my_sources', 'my_source') }}
```

### Rpc request

```sh
curl --request POST \
  --url http://localhost:8580/jsonrpc \
  --header 'Content-Type: application/json' \
  --data '{
    "jsonrpc": "2.0",
    "method": "cli_args",
    "id": "test-cli-args",
    "params": {
        "cli": "compile --vars '\''{db_name: development}'\''"
    }
}
'
```

----

### dbt 0.21.0 (built in rpc)

Start rpc server with:
```sh
dbt rpc
```

Poll method results:
![image](https://user-images.githubusercontent.com/8496748/146701965-0402710a-fd71-4906-a851-bd34ed5d82d0.png)

----

### dbt-core 1.0.0 + dbt-rpc 0.1.1

Start rpc server with:
```sh
dbt-rpc serve
```

Poll method results:
![image](https://user-images.githubusercontent.com/8496748/146702315-2ddf66d6-b403-401f-b79d-2982ea01a8ac.png)

----

### Workarounds

Use env_var like so:

```yml
# sources.yml
version: 2

sources:
  - name: my_sources
    database: "{{ env_var('DBT_DB_NAME', 'foo') }}"
    schema: dbt_jyeo
    tables:
      - name: my_source
```

Then set `DBT_DB_NAME` environment variable in dbt Cloud or `export DBT_DB_NAME=xyz` in dbt CLI.

**Comment by jtcohen6** [comment]
There are two bugs reported here:
1. [Original description] If vars are used in dbt_project.yml, to define resource config, that config isn't re-rendered when vars change. This was an issue in older versions, and it's still an issue
2. @jeremyyeo's comment / dbt-labs/dbt-core#4583: If vars are used in config within resource files (such as `snapshots/file.sql`), those resources aren't re-parsed when vars change. This was a regression in v1.0, and it was fixed by #70.

I believe the original issue is still present, even with the fix in #70

**Comment by BrJan** [comment]
Hi, can we get an update on this? Thanks!

**Comment by jtcohen6** [comment]
We're not going to resolve this in `dbt-rpc`, which is still slated for deprecation. Solving this issue requires fundamentally different architectural considerations. We are planning to solve for this when we add `--vars` support in `dbt-server`.

**Comment by nataliefiann** [comment]
Thanks for the update Jeremy, do you know roughly when that'll be?

**Comment by patkearns10** [comment]
Looks like it is slated for v1.5 second half of 2023: https://docs.getdbt.com/reference/commands/rpc
