### ISSUE TITLE
Recommended way to install

### ISSUE THREAD

**Issue by pgrivachev** [dbt-labs/dbt-rpc#67]
What is the recommended way to install `dbt-rpc` on mac and linux? I can't find this information either in [dbt docs](https://docs.getdbt.com/dbt-cli/install/overview) or [dbt-rpc docs](https://docs.getdbt.com/reference/commands/rpc).

I assume that using `pip`. Also, I have not found a way to install it through the homebrew.

**Comment by jtcohen6** [comment]
@pgrivachev Thanks for opening the issue! You're right, this isn't well documented today.

Installation via `pip` is definitely the right move:
```
pip install dbt-rpc
```

We don't have any plans to support installation via other methods, such as Homebrew or Docker.

We should add a note about this to the readme of this repository at the very least. I think it would be a good idea to mention explicitly in the [dbt-rpc docs](https://docs.getdbt.com/reference/commands/rpc) as well.
