### ISSUE TITLE
[CT-161] RPC server goes into infinitely compiling state when cancelling `dbt deps`

### ISSUE THREAD

**Issue by davidharting** [dbt-labs/dbt-rpc#71]
### Background

In the Cloud IDE, when you cancel a `dbt deps` command, the rpc server enters a compiling state and never comes out in my testing (after 5+ minutes). This appears to be a bug with dbt core or the RPC server, rather than cloud getting out of sync with the rpc server. The cloud IDe sends a “kill” command when the cancel button is clicked. As the IDE polls on `status`, it gets “compiling” back every time. So far, I have only been able to get this to happen with `deps` and no other commands.

### Reproduction steps

In dbt Cloud:
1. Start an IDE session
1. Make sure you are in a Ready state
1. Use the command bar to run `dbt deps`
1. Hit the Cancel button while it is running
1. Notice 
  1. That the deps command successfully cancels
  2. That the server is now in a compiling state and stays in that state

You can also watch me repro this in [this Loom](https://www.loom.com/share/74032c11ed514ac38243a8fa7ccabe02).

#### Expected behavior

I expect the server to go to _compiling_ momentarily after cancelling, but to then finish compiling and enter either an _error_ or _ready_ state.

**Comment by jtcohen6** [comment]
I was able to reproduce this with `dbt-rpc` locally. My suspicion is:
- `deps` is an instance of [`BlocksManifestTasks`](https://github.com/dbt-labs/dbt-rpc/blob/5793d59211803aab65acf21c2cb09408fd59607a/dbt_rpc/contracts/rpc.py#L508-L515) (i.e. it has [both flags `RequiresConfigReloadBefore` + `RequiresManifestReloadAfter`](https://github.com/dbt-labs/dbt-rpc/blob/5793d59211803aab65acf21c2cb09408fd59607a/dbt_rpc/task/deps.py#L23-L27))
- For manifest-blocking tasks, compilation cannot finish (= return to "ready" status) until the task has completed. [See the logic here](https://github.com/dbt-labs/dbt-rpc/blob/5793d59211803aab65acf21c2cb09408fd59607a/dbt_rpc/rpc/task_handler.py#L185-L193)
- When the task is killed (akin to keyboard interrupt), it never completes (either success or error), and so it never exits the [`set_parse_state_with` context manager](https://github.com/dbt-labs/dbt-rpc/blob/5793d59211803aab65acf21c2cb09408fd59607a/dbt_rpc/rpc/task_handler.py#L156-L170)

(I'm sure I'm slightly off for a few of the finer details)

You can _also_ watch me repro in [this Loom](https://www.loom.com/share/46b39b2536d048e98999133d69385247) :)

**Comment by davidharting** [comment]
@jtcohen6 Lol, the matching sweatshirt Loom 😆 Thanks so much for the reproduction and analysis! I need to get my local dbt set up restored so that I can provide local repro for this sort of thing!

**Comment by iknox-fa** [comment]
We have a few issues regarding dbt not handling inturrupts well.. Spike has been made to investigate further:
https://github.com/dbt-labs/dbt-rpc/issues/83
