### ISSUE TITLE
[CT-280] Support `--version` as a `cli_args` method

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-rpc#74]
This would need to work differently from other tasks, but it would be immensely valuable — especially now that we're auto-upgrading users to latest stable patch releases in dbt Cloud.

Exit criteria:
- Standalone `version` RPC method works — maybe this is a builtin, like `status`?
- Users can pass `version` or `--version` into `cli_args` task, and it hooks into the `version` method
- [Bonus] We also report the `dbt_rpc` version

Will add more details if/as I get a chance to poke around

**Comment by jtcohen6** [comment]
@iknox-fa Good call! Opened dbt-labs/dbt-core#5125 to represent the core piece of this, so that this ticket can represent just exposing that version task/info in `dbt-rpc`

**Comment by leahwicz** [comment]
We are just not going to get to this work so closing out
