### ISSUE TITLE
[CT-350] Memory leak with repeated compiles

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt-rpc#75]
dbt in rpc mode appears to leak memory as commands are executed, increasing during command execution, but then not falling back to the original memory usage following the command execution.

In this example, tracking the RAM in a container running dbt in rpc mode, you see this phenomenon -- the peaks are runs of the `dbt compile` command where the effect is most pronounced, but we also see this with partial parse re-compiles, DAG rendering via the DAG-in-IDE feature in dbt Cloud, file save operations, etc.

![Screen Shot 2022-03-10 at 9 16 28 PM](https://user-images.githubusercontent.com/74067474/157795438-a43b203a-352f-4ca6-bd26-adb2880a4766.png)

**Comment by ChenyuLInx** [comment]
The issue is caused by keeping a record of too many previous request results. We have garbage collection logic implemented but need to reduce the limit on things we keep in memory

**Comment by davidharting** [comment]
Thanks for this fix @ChenyuLInx!
