### ISSUE TITLE
[CT-759] Placing exceptions.raise_compiler_error call in generate_schema_name hangs when attempting to get raw_sql

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt-rpc#86]
If you are attempting to instrument your `generate_schema_name` macro with a call to `exceptions.raise_compiler_error` to throw a compile error if one of your models has a non-compliant schema, this will cause an unhandled exception in the rpc when attempting to access `node.path` of `rpc/request` 

To reproduce in dbt Cloud:

Drop the following code into a macro in dbt Cloud:

```
{% macro generate_schema_name(schema_name, node) -%}
    {{ generate_schema_name_for_env(schema_name) }}
    {% if node.path == 'rpc/request' %}
        {{ exceptions.raise_compiler_error("Blammo") }} 
    {% endif %}
{%- endmacro %}
```

and save.  

Remove your target folder.  

Select one of your models (or any .sql file for that matter) and click Compile... 

and watch the IDE go into spinner -- and there is a crasher behind the scenes with:

`AttributeError: 'ParsedMacro' object has no attribute 'raw_sql'`

**Comment by barberscott** [comment]
A workaround is to gate the `{{ exceptions.raise_compiler_error("...") }}` macro with `{% if node.path != 'rpc/request' %}` but it's not clear to me why a node with `rpc/request` is tripping over this macro in the first place.

**Comment by leahwicz** [comment]
@barberscott what priority would you put on this? Just trying to juggle where to put this in the backlog

**Comment by barberscott** [comment]
This has a workaround but it *is* difficult for folks to isolate in dbt Cloud without support's assistance.  I'd say medium to low priority especially if this will no longer be an issue post-RPC.
