### ISSUE TITLE
[CT-760] No logs returned

### ISSUE THREAD

**Issue by eugene-nikolaev** [dbt-labs/dbt-rpc#87]
Hi!

I could not manage to see the logs in responses despite of setting `logs=True`.

Does the following line mean dbt-rpc always returns logs as an empty array as opposed to [the docs](https://docs.getdbt.com/reference/commands/rpc#poll)?

https://github.com/dbt-labs/dbt-rpc/blob/2bbb0a39ef937eaf3b2c3cb2459ebe3abbbaaa8f/dbt_rpc/task/base.py#L41

**Comment by jtcohen6** [comment]
@eugene-nikolaev I think you need to enable the "legacy logger" for this to work, since the RPC server still doesn't support dbt-core's new logging system (#82).

That can be enabled with an environment variable:
```
DBT_ENABLE_LEGACY_LOGGER=True dbt-rpc serve
```

**Comment by eugene-nikolaev** [comment]
@jtcohen6, thanks a lot!
Now everything works as before

**Comment by eugene-nikolaev** [comment]
Hi, thanks for the reply!

So pity, previously it returned all the dbt logs and it was quite handy to
organize nightly tests. Now it is able only to return success/failure
status which is way less informative :(
