### ISSUE TITLE
[CT-1002] rpc infinite compile / running state on `dbt.exceptions.MacroReturn`

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-rpc#92]
Add a model (on disk) with a syntax error in the `call statement` and then try to `return` the `load_result`:

```jinja
-- models/bar.sql
{%- call statement('stat', fetch_result=True) -%}
selec 1
{%- endcall %}

{% set foo = load_result('stat').table.columns[0].values() %}

-- {{ return(foo) }}
```

> Specifically the above `select` is missing the `t`.

### Starting the rpc server when `return` is already in the file/on-disk

![image](https://user-images.githubusercontent.com/8496748/183314832-f4123fc2-e1e7-4b68-943d-7e89dba682ab.png)

^ Status is permanently compiling.

### While the rpc server is running and `return` not yet in file/on-disk

Start with

```jinja
-- models/bar.sql
{%- call statement('stat', fetch_result=True) -%}
selec 1
{%- endcall %}

{% set foo = load_result('stat').table.columns[0].values() %}
```

![image](https://user-images.githubusercontent.com/8496748/183314930-50f86ef3-ec68-4af8-84c7-3a15e6b0c6eb.png)

^ rpc is ready.

Now add our return:

```jinja
-- models/bar.sql
{%- call statement('stat', fetch_result=True) -%}
selec 1
{%- endcall %}

{% set foo = load_result('stat').table.columns[0].values() %}

-- {{ return(foo) }}
```

Submit a `compile` task:

![image](https://user-images.githubusercontent.com/8496748/183315104-41873427-a0d8-4428-bfe0-f1ddbff76e17.png)

Poll task state:

![image](https://user-images.githubusercontent.com/8496748/183315122-38b944bf-dc7c-44af-b174-b13cf892ee54.png)

^ Doesn't actually get out of the `running` state.

Check `ps`:

![image](https://user-images.githubusercontent.com/8496748/183315148-29405563-5e9e-4e2f-b47e-aaa6fd3e9a1f.png)

----

In dbt Cloud, if rpc has a task that is in the "running" state (and the above makes it so that the task never stops running), then you can't do anything else (i.e. try the preview/compile button, command line box is also permanently not interactable).

![image](https://user-images.githubusercontent.com/8496748/183315240-613fc76a-fb48-477f-8a15-e9edb3b91b46.png)

^ Even if you remove the offending `return()` and then save your model file - the IDE is still in the same stuck state.

----

Probably relevant to the #83

**Comment by jtcohen6** [comment]
Thanks @jeremyyeo!

Looks similar to (though slightly different from) https://github.com/dbt-labs/dbt-rpc/issues/43, which was also an issue with `MacroReturn`. That one was encountered at parse time, rather than while executing a statement at runtime.

I don't know if we're likely to prioritize this, relative to our ongoing work developing a suitable replacement for the RPC Server.
