### ISSUE TITLE
[CT-1371] rpc doesn't use `--target-path` flag

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-rpc#97]
Not sure if we'd want to fix this or not (probably no) but raising anyway.

If you use the `--target-path` flag like so:

```
curl --request POST \
  --url http://localhost:8580/jsonrpc \
  --header 'Content-Type: application/json' \
  --data '{
    "jsonrpc": "2.0",
    "method": "cli_args",
    "id": "test-cli-args",
    "params": {
        "cli": "compile --target-path new_target"
    }
}
'
```

The compiled files and artifacts still go into `target/` instead of `new_target/`.

Some users in dbt Cloud who may want to use this flag will find that they cannot.

![image](https://user-images.githubusercontent.com/8496748/196571498-e4c35d74-3926-416f-8d71-8a56c19747de.png)

**Comment by misteliy** [comment]
This is indeed a feature that would solve to leverage defer and make it a first class citizen. In turn this would allow to fully be able to do local development… currently it is not possible :/

**Comment by jtcohen6** [comment]
Thanks for opening @jeremyyeo! We're not going to fix this, since the `dbt-rpc` server is nearing end of life, and we're planning to deprecate it / archive the repository in favor of a new `dbt-server`.

**Comment by misteliy** [comment]
will this then be possible in the new `dbt-server`?
